from fastapi import APIRouter

from app.api.routers import (
    admin,
    amenities,
    auth,
    availability,
    b2b,
    bookings,
    destinations,
    exchange_rates,
    extra_beds,
    finance,
    health,
    meta,
    packages,
    payments,
    programs,
    promotions,
    rate_plans,
    regions,
    reviews,
    room_availability,
    room_images,
    rooms,
    sanatorium_featured,
    sanatorium_images,
    sanatorium_search,
    sanatoriums,
    transfers,
    treatment_focuses,
    users,
)

api_router = APIRouter()
api_router.include_router(health.router)
api_router.include_router(meta.router)
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(sanatorium_search.router)
api_router.include_router(sanatorium_featured.router)
api_router.include_router(sanatoriums.router)
api_router.include_router(sanatorium_images.router)
api_router.include_router(rooms.router)
api_router.include_router(room_availability.router)
api_router.include_router(room_images.router)
api_router.include_router(exchange_rates.router)
api_router.include_router(bookings.router)
api_router.include_router(amenities.router)
api_router.include_router(programs.router)
api_router.include_router(promotions.router)
api_router.include_router(rate_plans.router)
api_router.include_router(packages.router)
api_router.include_router(extra_beds.router)
api_router.include_router(reviews.router)
api_router.include_router(availability.router)
api_router.include_router(payments.router)
api_router.include_router(finance.router)
api_router.include_router(admin.router)
api_router.include_router(b2b.router)
api_router.include_router(transfers.router)
api_router.include_router(treatment_focuses.router)
api_router.include_router(regions.router)
api_router.include_router(destinations.router)
