OPENAPI_TAGS = [
    {"name": "Identity", "description": "Authentication and user accounts"},
    {"name": "Sanatoriums", "description": "Sanatorium profiles, media, reviews"},
    {"name": "Destinations", "description": "Regions and destination tiles"},
    {"name": "Treatments", "description": "Treatment focuses and programs"},
    {"name": "Amenities", "description": "Amenity catalog"},
    {"name": "Rooms", "description": "Rooms, rate plans, extra beds, room media"},
    {"name": "Availability", "description": "Availability calendars and blocks"},
    {"name": "Promotions", "description": "Promotion campaigns and discounts"},
    {"name": "Bookings", "description": "Booking creation and management"},
    {"name": "Guest Relations", "description": "Review and guest question workflows"},
    {"name": "Packages", "description": "All-inclusive package journeys"},
    {"name": "Payments", "description": "Payments and exchange rates"},
    {"name": "Finance", "description": "Role-based finance reports"},
    {"name": "B2B", "description": "B2B agent dashboard and clients"},
    {"name": "Travel Services", "description": "Transfer requests"},
    {"name": "Admin", "description": "Admin dashboard and operational stats"},
    {"name": "System", "description": "Health checks and metadata"},
]
