OPENAPI_TAGS = [
    {"name": "auth", "description": "Login, register, refresh tokens"},
    {"name": "users", "description": "Profile and user management"},
    {"name": "sanatoriums", "description": "Sanatoriums and wellness centers"},
    {"name": "amenities", "description": "Amenity catalog"},
    {"name": "programs", "description": "Treatment and wellness programs"},
    {"name": "treatment-focuses", "description": "Treatment focus catalog"},
    {"name": "rooms", "description": "Rooms, availability, seasonal pricing"},
    {"name": "extra-beds", "description": "Extra bed configurations"},
    {"name": "bookings", "description": "Booking creation and management"},
    {"name": "reviews", "description": "Sanatorium reviews"},
    {"name": "exchange-rates", "description": "USD/UZS exchange rates"},
    {"name": "availability", "description": "Monthly availability calendar"},
    {"name": "payments", "description": "Payment initiation and webhooks"},
    {"name": "finance", "description": "Role-based finance reports"},
    {"name": "admin", "description": "Admin dashboard stats"},
    {"name": "b2b", "description": "B2B agent dashboard and clients"},
    {"name": "health", "description": "Health check"},
]
