"""create transfer_requests

Revision ID: 3132bf292c7d
Revises: c5d8e2f1a3b7
Create Date: 2026-05-21 22:40:17.118895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3132bf292c7d'
down_revision: Union[str, Sequence[str], None] = 'c5d8e2f1a3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.Enum('arrival', 'departure', 'round_trip', name='transferdirection', native_enum=False, length=20), nullable=False),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=True),
    sa.Column('flight_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('return_flight_number', sa.String(length=20), nullable=True),
    sa.Column('return_flight_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passengers_count', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('sedan', 'minivan', 'bus', name='vehicletype', native_enum=False, length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'completed', 'cancelled', name='transferstatus', native_enum=False, length=20), nullable=False),
    sa.Column('driver_name', sa.String(length=255), nullable=True),
    sa.Column('driver_phone', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_requests_booking_id'), 'transfer_requests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_transfer_requests_status'), 'transfer_requests', ['status'], unique=False)
    op.create_index(op.f('ix_transfer_requests_user_id'), 'transfer_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_requests_user_id'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_status'), table_name='transfer_requests')
    op.drop_index(op.f('ix_transfer_requests_booking_id'), table_name='transfer_requests')
    op.drop_table('transfer_requests')
    # ### end Alembic commands ###
