"""add pricing tiers, treatment programs, extra beds

Revision ID: 35a195039ba0
Revises: d27b0a6764ca
Create Date: 2026-05-12 22:22:17.622723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a195039ba0'
down_revision: Union[str, Sequence[str], None] = 'd27b0a6764ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_amenities_category'), 'amenities', ['category'], unique=False)
    op.create_table('extra_bed_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sanatorium_id', sa.Uuid(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sanatorium_id'], ['sanatoriums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extra_bed_configs_sanatorium_id'), 'extra_bed_configs', ['sanatorium_id'], unique=False)
    op.create_table('treatment_programs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sanatorium_id', sa.Uuid(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=False),
    sa.Column('max_nights', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sanatorium_id'], ['sanatoriums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_programs_sanatorium_id'), 'treatment_programs', ['sanatorium_id'], unique=False)
    op.create_table('program_amenities',
    sa.Column('program_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['treatment_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id', 'amenity_id')
    )
    op.create_table('booking_extra_beds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('config_id', sa.Uuid(), nullable=True),
    sa.Column('name_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_per_night_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['config_id'], ['extra_bed_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_extra_beds_booking_id'), 'booking_extra_beds', ['booking_id'], unique=False)
    op.add_column('room_categories', sa.Column('base_price_weekend', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('room_categories', sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_categories', 'discount_percent')
    op.drop_column('room_categories', 'base_price_weekend')
    op.drop_index(op.f('ix_booking_extra_beds_booking_id'), table_name='booking_extra_beds')
    op.drop_table('booking_extra_beds')
    op.drop_table('program_amenities')
    op.drop_index(op.f('ix_treatment_programs_sanatorium_id'), table_name='treatment_programs')
    op.drop_table('treatment_programs')
    op.drop_index(op.f('ix_extra_bed_configs_sanatorium_id'), table_name='extra_bed_configs')
    op.drop_table('extra_bed_configs')
    op.drop_index(op.f('ix_amenities_category'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
