"""uzum checkout callback events

Revision ID: 3ad7b0102e8b
Revises: bd519dd68b51
Create Date: 2026-08-05 13:35:48.676076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3ad7b0102e8b"
down_revision: Union[str, Sequence[str], None] = "bd519dd68b51"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "uzum_checkout_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "acquiring",
                "event",
                "receipt",
                name="uzumcheckoutcallbackkind",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("order_id", sa.String(length=64), nullable=True),
        sa.Column("order_number", sa.String(length=36), nullable=True),
        sa.Column("operation_type", sa.String(length=32), nullable=True),
        sa.Column("operation_state", sa.String(length=16), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=True),
        sa.Column("receipt_type", sa.String(length=16), nullable=True),
        sa.Column("receipt_url", sa.String(length=2083), nullable=True),
        sa.Column("rrn", sa.String(length=64), nullable=True),
        sa.Column("source_ip", sa.String(length=64), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_uzum_checkout_events_kind"),
        "uzum_checkout_events",
        ["kind"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uzum_checkout_events_order_id"),
        "uzum_checkout_events",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_uzum_checkout_events_order_number"),
        "uzum_checkout_events",
        ["order_number"],
        unique=False,
    )
    op.create_index(
        "ix_uzum_checkout_events_unprocessed",
        "uzum_checkout_events",
        ["processed_at", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_uzum_checkout_events_unprocessed", table_name="uzum_checkout_events"
    )
    op.drop_index(
        op.f("ix_uzum_checkout_events_order_number"), table_name="uzum_checkout_events"
    )
    op.drop_index(
        op.f("ix_uzum_checkout_events_order_id"), table_name="uzum_checkout_events"
    )
    op.drop_index(
        op.f("ix_uzum_checkout_events_kind"), table_name="uzum_checkout_events"
    )
    op.drop_table("uzum_checkout_events")
    # ### end Alembic commands ###
