"""booking rate plan snapshot

Revision ID: 40839c2e3a79
Revises: 7d5de2daedf1
Create Date: 2026-05-25 02:30:06.083771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40839c2e3a79'
down_revision: Union[str, Sequence[str], None] = '7d5de2daedf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('rate_plan_id', sa.Uuid(), nullable=True))
    op.add_column('bookings', sa.Column('board', sa.Enum('room_only', 'breakfast', 'half_board', 'full_board', 'all_inclusive', name='boardtype', native_enum=False, length=20), nullable=True))
    op.add_column('bookings', sa.Column('refundable', sa.Boolean(), nullable=True))
    op.add_column('bookings', sa.Column('free_cancellation_days', sa.Integer(), nullable=True))
    op.add_column('bookings', sa.Column('cancellation_penalty_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('payment_timing', sa.Enum('prepay', 'at_hotel', 'deposit', name='paymenttiming', native_enum=False, length=20), nullable=True))
    op.create_index(op.f('ix_bookings_rate_plan_id'), 'bookings', ['rate_plan_id'], unique=False)
    op.create_foreign_key('fk_bookings_rate_plan_id', 'bookings', 'rate_plans', ['rate_plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bookings_rate_plan_id', 'bookings', type_='foreignkey')
    op.drop_index(op.f('ix_bookings_rate_plan_id'), table_name='bookings')
    op.drop_column('bookings', 'payment_timing')
    op.drop_column('bookings', 'cancellation_penalty_percent')
    op.drop_column('bookings', 'free_cancellation_days')
    op.drop_column('bookings', 'refundable')
    op.drop_column('bookings', 'board')
    op.drop_column('bookings', 'rate_plan_id')
    # ### end Alembic commands ###
