"""rate_plans table

Revision ID: 7d5de2daedf1
Revises: b9c89fb53e6f
Create Date: 2026-05-25 02:24:30.346090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d5de2daedf1'
down_revision: Union[str, Sequence[str], None] = 'b9c89fb53e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('board', sa.Enum('room_only', 'breakfast', 'half_board', 'full_board', 'all_inclusive', name='boardtype', native_enum=False, length=20), nullable=False),
    sa.Column('board_optional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('board_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('refundable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('free_cancellation_days', sa.Integer(), nullable=True),
    sa.Column('cancellation_penalty_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('payment_timing', sa.Enum('prepay', 'at_hotel', 'deposit', name='paymenttiming', native_enum=False, length=20), nullable=False),
    sa.Column('confirmation', sa.Enum('instant', 'on_request', name='confirmationtype', native_enum=False, length=20), nullable=False),
    sa.Column('price_adjustment_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('max_nights', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_plans_room_id'), 'rate_plans', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_plans_room_id'), table_name='rate_plans')
    op.drop_table('rate_plans')
    # ### end Alembic commands ###
