"""create visa_requests

Revision ID: 844708bf396d
Revises: b3c4d5e6f7a8
Create Date: 2026-05-20 22:24:40.224261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844708bf396d'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visa_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('citizenship', sa.String(length=120), nullable=False),
    sa.Column('passport_number', sa.String(length=64), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.Enum('tourism', 'treatment', 'business', 'other', name='visapurpose', native_enum=False, length=20), nullable=False),
    sa.Column('passport_scan_url', sa.String(length=500), nullable=True),
    sa.Column('issued_document_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'issued', 'rejected', name='visastatus', native_enum=False, length=20), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visa_requests_booking_id'), 'visa_requests', ['booking_id'], unique=False)
    op.create_index(op.f('ix_visa_requests_status'), 'visa_requests', ['status'], unique=False)
    op.create_index(op.f('ix_visa_requests_user_id'), 'visa_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visa_requests_user_id'), table_name='visa_requests')
    op.drop_index(op.f('ix_visa_requests_status'), table_name='visa_requests')
    op.drop_index(op.f('ix_visa_requests_booking_id'), table_name='visa_requests')
    op.drop_table('visa_requests')
    # ### end Alembic commands ###
