"""sanatorium venues + meal schedule

Revision ID: 8bda2dd3cac0
Revises: a686a9615492
Create Date: 2026-05-25 03:19:11.164223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bda2dd3cac0'
down_revision: Union[str, Sequence[str], None] = 'a686a9615492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sanatoriums', sa.Column('venues', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('sanatoriums', sa.Column('meal_schedule', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sanatoriums', 'meal_schedule')
    op.drop_column('sanatoriums', 'venues')
    # ### end Alembic commands ###
