"""promo, penalties, sanatorium header, review subscores

Revision ID: a686a9615492
Revises: f9aa50a48a96
Create Date: 2026-05-25 03:14:34.265230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a686a9615492'
down_revision: Union[str, Sequence[str], None] = 'f9aa50a48a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('cancellation_penalty_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('original_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('bookings', sa.Column('promo_percent_snapshot', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('rate_plans', sa.Column('cancellation_penalty_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('rate_plans', sa.Column('promo_label', sa.String(length=60), nullable=True))
    op.add_column('rate_plans', sa.Column('promo_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('rate_plans', sa.Column('promo_starts_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rate_plans', sa.Column('promo_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sanatorium_reviews', sa.Column('traveler_type', sa.String(length=30), nullable=True))
    op.add_column('sanatorium_reviews', sa.Column('cleanliness', sa.SmallInteger(), nullable=True))
    op.add_column('sanatorium_reviews', sa.Column('location', sa.SmallInteger(), nullable=True))
    op.add_column('sanatorium_reviews', sa.Column('service', sa.SmallInteger(), nullable=True))
    op.add_column('sanatorium_reviews', sa.Column('value', sa.SmallInteger(), nullable=True))
    op.add_column('sanatorium_reviews', sa.Column('food', sa.SmallInteger(), nullable=True))
    op.add_column('sanatoriums', sa.Column('year_opened', sa.SmallInteger(), nullable=True))
    op.add_column('sanatoriums', sa.Column('languages_spoken', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('sanatoriums', sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('sanatoriums', sa.Column('surroundings', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sanatoriums', 'surroundings')
    op.drop_column('sanatoriums', 'highlights')
    op.drop_column('sanatoriums', 'languages_spoken')
    op.drop_column('sanatoriums', 'year_opened')
    op.drop_column('sanatorium_reviews', 'food')
    op.drop_column('sanatorium_reviews', 'value')
    op.drop_column('sanatorium_reviews', 'service')
    op.drop_column('sanatorium_reviews', 'location')
    op.drop_column('sanatorium_reviews', 'cleanliness')
    op.drop_column('sanatorium_reviews', 'traveler_type')
    op.drop_column('rate_plans', 'promo_ends_at')
    op.drop_column('rate_plans', 'promo_starts_at')
    op.drop_column('rate_plans', 'promo_percent')
    op.drop_column('rate_plans', 'promo_label')
    op.drop_column('rate_plans', 'cancellation_penalty_amount')
    op.drop_column('bookings', 'promo_percent_snapshot')
    op.drop_column('bookings', 'original_price')
    op.drop_column('bookings', 'cancellation_penalty_amount')
    # ### end Alembic commands ###
