"""room physical attributes + room_images

Revision ID: b9c89fb53e6f
Revises: d4e8f1a6c2b3
Create Date: 2026-05-25 02:14:11.131796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9c89fb53e6f'
down_revision: Union[str, Sequence[str], None] = 'd4e8f1a6c2b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_video', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_images_room_id'), 'room_images', ['room_id'], unique=False)
    op.add_column('rooms', sa.Column('size_sqm', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('beds', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('rooms', sa.Column('view', sa.Enum('city', 'sea', 'garden', 'mountain', 'pool', 'lake', 'park', 'courtyard', 'street', 'landmark', name='roomview', native_enum=False, length=20), nullable=True))
    op.add_column('rooms', sa.Column('smoking_allowed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rooms', sa.Column('max_adults', sa.SmallInteger(), nullable=True))
    op.add_column('rooms', sa.Column('max_children', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'max_children')
    op.drop_column('rooms', 'max_adults')
    op.drop_column('rooms', 'smoking_allowed')
    op.drop_column('rooms', 'view')
    op.drop_column('rooms', 'beds')
    op.drop_column('rooms', 'size_sqm')
    op.drop_index(op.f('ix_room_images_room_id'), table_name='room_images')
    op.drop_table('room_images')
    # ### end Alembic commands ###
