"""add sanatorium facilities, reviews, room amenities

Revision ID: c3765ad10e35
Revises: 35a195039ba0
Create Date: 2026-05-12 22:39:08.589458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3765ad10e35'
down_revision: Union[str, Sequence[str], None] = '35a195039ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanatorium_amenities',
    sa.Column('sanatorium_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sanatorium_id'], ['sanatoriums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sanatorium_id', 'amenity_id')
    )
    op.create_table('sanatorium_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sanatorium_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=120), nullable=False),
    sa.Column('reviewer_country', sa.String(length=60), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sanatorium_id'], ['sanatoriums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanatorium_reviews_sanatorium_id'), 'sanatorium_reviews', ['sanatorium_id'], unique=False)
    op.add_column('room_categories', sa.Column('room_amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('sanatoriums', sa.Column('phone', sa.String(length=30), nullable=True))
    op.add_column('sanatoriums', sa.Column('treatment_focuses', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('sanatoriums', sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('sanatoriums', sa.Column('review_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sanatoriums', 'review_count')
    op.drop_column('sanatoriums', 'avg_rating')
    op.drop_column('sanatoriums', 'treatment_focuses')
    op.drop_column('sanatoriums', 'phone')
    op.drop_column('room_categories', 'room_amenities')
    op.drop_index(op.f('ix_sanatorium_reviews_sanatorium_id'), table_name='sanatorium_reviews')
    op.drop_table('sanatorium_reviews')
    op.drop_table('sanatorium_amenities')
    # ### end Alembic commands ###
