"""create room_categories, exchange_rates, room_availability tables

Revision ID: d1171c2d0a7a
Revises: 2151a795820b
Create Date: 2026-05-11 17:02:33.574524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1171c2d0a7a'
down_revision: Union[str, Sequence[str], None] = '2151a795820b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pair', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_pair'), 'exchange_rates', ['pair'], unique=True)
    op.create_table('room_categories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sanatorium_id', sa.Uuid(), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capacity', sa.SmallInteger(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('markup_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_nights', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sanatorium_id'], ['sanatoriums.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_categories_sanatorium_id'), 'room_categories', ['sanatorium_id'], unique=False)
    op.create_table('room_availability',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_category_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=False),
    sa.Column('units_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_category_id'], ['room_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_category_id', 'date', name='uq_room_availability_date')
    )
    op.create_index(op.f('ix_room_availability_date'), 'room_availability', ['date'], unique=False)
    op.create_index(op.f('ix_room_availability_room_category_id'), 'room_availability', ['room_category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_availability_room_category_id'), table_name='room_availability')
    op.drop_index(op.f('ix_room_availability_date'), table_name='room_availability')
    op.drop_table('room_availability')
    op.drop_index(op.f('ix_room_categories_sanatorium_id'), table_name='room_categories')
    op.drop_table('room_categories')
    op.drop_index(op.f('ix_exchange_rates_pair'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
