"""room/sanatorium amenity links + physical & policy fields

Revision ID: f9aa50a48a96
Revises: 40839c2e3a79
Create Date: 2026-05-25 03:02:15.020479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9aa50a48a96'
down_revision: Union[str, Sequence[str], None] = '40839c2e3a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_amenities',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('amenity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'amenity_id')
    )
    op.add_column('rate_plans', sa.Column('board_guests', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('floor', sa.String(length=20), nullable=True))
    op.drop_column('rooms', 'room_amenities')
    op.add_column('sanatorium_amenities', sa.Column('cost', sa.Enum('free', 'paid', 'on_request', name='amenitycost', native_enum=False, length=20), server_default='free', nullable=False))
    op.add_column('sanatorium_amenities', sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('sanatoriums', sa.Column('pets_allowed', sa.Boolean(), nullable=True))
    op.add_column('sanatoriums', sa.Column('service_animals_allowed', sa.Boolean(), nullable=True))
    op.add_column('sanatoriums', sa.Column('min_checkin_age', sa.SmallInteger(), nullable=True))
    op.add_column('sanatoriums', sa.Column('quiet_hours_from', sa.Time(), nullable=True))
    op.add_column('sanatoriums', sa.Column('quiet_hours_to', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sanatoriums', 'quiet_hours_to')
    op.drop_column('sanatoriums', 'quiet_hours_from')
    op.drop_column('sanatoriums', 'min_checkin_age')
    op.drop_column('sanatoriums', 'service_animals_allowed')
    op.drop_column('sanatoriums', 'pets_allowed')
    op.drop_column('sanatorium_amenities', 'is_available')
    op.drop_column('sanatorium_amenities', 'cost')
    op.add_column('rooms', sa.Column('room_amenities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'floor')
    op.drop_column('rate_plans', 'board_guests')
    op.drop_table('room_amenities')
    # ### end Alembic commands ###
